test_pairwise_features (test_features.FeatureTests) ... ok
test_unary_features (test_features.FeatureTests) ... ok
test_belief_convergence (test_beliefs.BeliefTests) ... ok
test_pairwise_beliefs (test_beliefs.BeliefTests) ... FAIL
test_inf (test_inference.InferenceTests) ... ok
test_local_score (test_inference.InferenceTests) ... FAIL
test_learning_obj (test_learning.LearningTests) ... 2018-04-01 20:30:08.969482: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
FAIL
test_pairwise_potentials (test_potentials.PotentialTests) ... ok
test_unary_potentials (test_potentials.PotentialTests) ... ok

======================================================================
FAIL: test_pairwise_beliefs (test_beliefs.BeliefTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cs446grader/autograder/mp7_programming/submissions/ryang28/tests_autograder/test_beliefs.py", line 60, in test_pairwise_beliefs
    np.testing.assert_array_equal(correct, result)
  File "/home/cs446grader/grading_env/lib/python3.4/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/cs446grader/grading_env/lib/python3.4/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 12.5%)
 x: array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])
 y: array([[0., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

======================================================================
FAIL: test_local_score (test_inference.InferenceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cs446grader/autograder/mp7_programming/submissions/ryang28/tests_autograder/test_inference.py", line 124, in test_local_score
    self.assertEqual(result, 0)
AssertionError: 4.0 != 0

======================================================================
FAIL: test_learning_obj (test_learning.LearningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cs446grader/autograder/mp7_programming/submissions/ryang28/tests_autograder/test_learning.py", line 91, in test_learning_obj
    self.assertEqual(correct, result_val)
AssertionError: -4.0 != 36.0

----------------------------------------------------------------------
Ran 9 tests in 0.239s

FAILED (failures=3)
